# Format prompt
format = """
$directory\
$aws\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$helm\
$python
$jobs$shlvl$character"""

#right_format = """
#$aws\
#$kubernetes\
#$git_branch\
#$git_commit\
#$git_state\
#$git_metrics\
#$git_status\
#$helm\
#$status
#"""

# Set command_timeout to higher value
command_timeout = 2000

#add_newline = false
#palette = "catppuccin_mocha"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = '🅰 '

[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = '…/'

[kubernetes]
format = '[$symbol\($namespace\)](yellow) '
disabled = false
#symbol = '☸  '
#contexts = [
#  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
#]

[shlvl]
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
